# Generated by Django 6.0.5 on 2026-06-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_before',
            field=models.PositiveBigIntegerField(choices=[(0, 'at exact Time'), (5, '5 Minutes Before'), (10, '10 Minutes Before'), (15, '15 Minutes Before'), (20, '20 Minutes Before'), (30, '30 Minutes Before')], default=0, help_text='Reminder time in minutes before task'),
        ),
    ]
