# Generated by Django 6.0.6 on 2026-06-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_reminded',
            field=models.BooleanField(default=False),
        ),
    ]
