# Generated by Django 6.0.6 on 2026-06-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_is_reminded'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alarm_pending',
            field=models.BooleanField(default=False),
        ),
    ]
